<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DATELE_PERSONALE [
<!ELEMENT DATELE_PERSONALE (NUME, PRENUME, DATA_NASTERII, LOCUL_NASTERII , SEXUL, STARE_CIVILA ,CNP)>
<!ELEMENT NUME (#PCDATA)>
<!ELEMENT PRENUME (#PCDATA)>
<!ELEMENT DATA_NASTERII (#PCDATA)>
<!ELEMENT LOCUL_NASTERII (#PCDATA)>
<!ELEMENT SEXUL (#PCDATA)>
<!ELEMENT CNP (#PCDATA)>
<!ELEMENT STARE_CIVILA (CASATORITE, NECASATORITE ,DIVORTAT)>
<!ELEMENT CASATORITE (#PCDATA)>
<!ELEMENT NECASATORITE (#PCDATA)>
<!ELEMENT DIVORTAT (#PCDATA)>

]>

<DATELE_PERSONALE>
    
    <NUME>SEED</NUME>
    
    <PRENUME>KENAN</PRENUME>
    
    <DATA_NASTERII>23/06/1997</DATA_NASTERII>
    
    <LOCUL_NASTERII>SYRIA</LOCUL_NASTERII>
    
    <SEXUL>MASCULIN</SEXUL>
    
    
    <!---<STARE_CIVILA>NECASATORITE</STARE_CIVILA>-->
    <STARE_CIVILA>
        
        <CASATORITE>NU</CASATORITE>
        
        <NECASATORITE>DA</NECASATORITE>
        
        <DIVORTAT>NU</DIVORTAT>
        
    </STARE_CIVILA>
    
    <CNP>727323061997</CNP>
    
</DATELE_PERSONALE>